### ISSUE TITLE
country names

### ISSUE THREAD

**Issue by ghost** [markuslerner/travelscope#1]
how can I get country names after particular amount of zoom?

**Comment by markuslerner** [comment]
Dear Akshay,

can you please elaborate a bit more on your question? I don’t quite understand what you’re trying to do.

Best
Markus

**Comment by ghost** [comment]
just take example.

I am zooming into the world map in flat view.
at a particular zoom level, map should show names of country.

if we zoom into map for 50% then it should show names of country on the country.
like it is america then text 'america' should be shown in only on the america country part.

**Comment by markuslerner** [comment]
Hi Akshay,

now I know what you mean.

This is a function you would have to implement yourself.

Basically you would have to take the country's center2D or center3D position (2D/3D map view center in three.js), transform it to a 2D screen position:

var pos2D = projector.projectVector( center2D, camera );

And then draw an HTML label element with the country name in that position.

Alternatively you can use a map library, which makes it easier to do that, like OpenLayers:
https://openlayers.org/en/latest/examples/vector-label-decluttering.html?q=label <https://openlayers.org/en/latest/examples/vector-label-decluttering.html?q=label>

Best
Markus

**Comment by ghost** [comment]
any idea where to put this function in the existing files?

**Comment by markuslerner** [comment]
Hi Akshay,

In index.js > createCountries() I would create a function before window.setTimeout() that iterates over all the countries:

for(i = 0; i < this.countries.length; i++) {
	// create html labels (e.g. using jQuery) with country.name and absolute positions using center2D (like in my previous e-mail)
}

Then you would have to update the positions of the html labels when the controls have changed:

In index.js > initControls():

this.controlsPinchZoom.addEventListener('change', function() {
	// interate over all the countries and update html label positions
});

I haven't tested it, but it should work like this.

Good luck!
Markus

**Comment by ghost** [comment]
Okay.

Ill try this one.
Actually I am new to three.js and other things.
I didn't found any thing related to find center point of a shape, can you help me in this?

**Comment by markuslerner** [comment]
> I didn't found any thing related to find center point of a shape, can you help me in this?
> 

The center point I have already calculated (country.center2D and country.center3D), like I have written to you before:

"Basically you would have to take the country's center2D or center3D position (2D/3D map view center in three.js), transform it to a 2D screen position:

var pos2D = projector.projectVector( center2D, camera );

And then draw an HTML label element with the country name in that position."

Best
Markus
