### ISSUE TITLE
Chile/Atacama corridor

### ISSUE THREAD

**Issue by thwd** [markuslerner/travelscope#10]
The Chile/Atacama corridor area in travelscope's map is marked as disputed territory. This is wrong. This land has been both de-facto and de-jure territory of Chile alone, since 1904.

Bolivia asked the UN, in 2018, for _any_ corridor of land through Chile's territory that would give them access to the pacific ocean. The UN said no.

This antecedent doesn't make any specific part of Chile's territory disputed, much less 1/6th of its total area.

**Comment by markuslerner** [comment]
Thank you for pointing this out.

I'm using the disputed area map from Natural Earth Data.

If you have any corrections, please submit them here:
https://www.naturalearthdata.com/corrections/ <https://www.naturalearthdata.com/corrections/>

Best
Markus

**Comment by thwd** [comment]
I tried to submit a ticket at that link but there seems to be a persistent database connection error on their end.
