### ISSUE TITLE
Incorrect maps of Ukraine without Crimea

### ISSUE THREAD

**Issue by oborys** [markuslerner/travelscope#4]
This site https://www.markuslerner.com/ display maps of Ukraine without Crimea.
Crimea is part of Ukraine, please fix your map.
Link on official United Nation documents that reaffirmed Ukraine’s unity and territorial integrity
https://undocs.org/a/68/l.39

Ukranian law regarding Crimea:
http://zakon2.rada.gov.ua/laws/show/1207-vii

Thank you.

**Comment by markuslerner** [comment]
Thank you for pointing this out. I use the cultural vector data from https://www.naturalearthdata.com/downloads/ <https://www.naturalearthdata.com/downloads/>, which includes Crimea as part of Russia. I don't change the country assignment of the map shapes.

naturalearthdata.com <http://naturalearthdata.com/> claims: "Natural Earth Vector draws boundaries of countries according to defacto status. We show who actually controls the situation on the ground. [...]"

I'm planning to add a disputed area map as soon as possible.

Markus
