### ISSUE TITLE
Add support for multiple citizenship

### ISSUE THREAD

**Issue by diogosalazar** [markuslerner/travelscope#6]
Hi,

Would love to have the ability to define a set of source countries and see how many total destinations would be available for that set of source countries. This would be the case for people who hold multiple (2, 3 or more) citizenships.

Thank you.

**Comment by markuslerner** [comment]
Thank you, that's a good idea. There is an offspring project in development called TravelPathway, which is going to implement that:
https://travelpathway.world <https://travelpathway.world/>

Best
Markus
