### ISSUE TITLE
Adding layers to the map

### ISSUE THREAD

**Issue by NORLISA** [markuslerner/travelscope#8]
Hi Markus,

Recently, I've encountered an error loading visa requirements data as attached. Thus, may I know what is the possible cause for this issue? 
Besides that, how can I add/overlay an additional layer to the map? 

![error in data loading](https://user-images.githubusercontent.com/17564688/55208736-47476780-521a-11e9-801f-7ea382d4d708.png)

Thank you.

**Comment by markuslerner** [comment]
Hello Lily,

the data folder is not checked in to the repository. Please pull the latest commit. I changed the url to pull the data from the CDN.

Unfortunately adding another layer is not so easily possible. You could create your own mesh and geometry object and add it to the scene like in line 558 in geometry js:

var mesh = new THREE.Mesh( worldMap.bufferGeometry, Config.materialMap );
worldMap.scene.add( mesh );

Best
Markus
